name: Gaurish Sharma Live | Sharing What I Have Learned
description: Gaurish Sharma Live is a place where I Share My Learnings
url: www.gaurishsharma.com
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title.html
post:
  template: _layouts/post.html
  extension: markdown
