name: Gaurish Sharma Live | Sharing What I Have Learned
description: Gaurish Sharma Live is a place where I Share My Learnings
markdown: redcarpet
highlighter: rouge
permalink: /:year/:month/:title.html

url: http://www.gaurishsharma.com
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

plugins:
  - jekyll-gist
