name: Gaurish Sharma Live | Sharing What I Have Learned
title: Gaurish Sharma Live | Sharing What I Have Learned
description: Gaurish Sharma Live is a place where I Share My Learnings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html
url: http://www.gaurishsharma.com
baseurl:
plugins:
  - jekyll-gist
  - jekyll-admin
